name = "GraphColoring"
uuid = "2eaf82eb-f9ae-4d9b-a5af-4a8051fbc35e"
authors = ["djukic14 <danijel.jukic14@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test"]
